timeout = 30000
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = true
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.instagram]
disabled = true
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true