largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# directory(s) where your articles are located
mainSections = ["post"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

logo = "logos/logo-dev.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally

# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# Light Mode
enforceLightMode = false
enforceDarkMode = false

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
footerLogo = "icons/footer.png"

# Text for the languages menu.
languageMenuName = "ðŸŒ"

# Enable or disable comments globally. Default to true.
comments = true

# Maximum number of recent posts.
numberOfRecentPosts = 8

# Maximum number of featured posts.
numberOfFeaturedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = false # toggle to true if you want to use custom fonts only.

# The year when ths website was created, this value is used in the copyright
# notice of the footer.
since = 2021

# tell hugo where you store your icons e.g favicons. This is useful if you're using an apache server and there are conflicts >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory 
iconsDir = "icons/" # without a leading forward slash

[plausible_analytics]
enable = false # to enable plausible analytics set to true.
# websiteDomain = "" # domain name of your website, most cases same as your base url
# plausibleDomain = "plausible.io" # default is set to plausible.io, only required if plausible is selfhosted
# scritpName = "plausible" # default is set to plausible, only required if using a custome name for script

[matomo_analytics]
enable = false # To enable matomo analytics change to `true`.
# websiteDomain = "example.com" # Set the domain name of your website, in most cases same as your base URL this is required.
# matomoDomain = "matomo.example.com" # Set to Matomo domain
# matomoSiteID = "1" # Default is set to 1, change this to the siteid being tracked